
INSERT INTO COMPANY (NAME, ADDRESS, CITY, COUNTRY, EMAIL, PHONE_NUMBER)
VALUES ('naderihub', 'behan square', 'dublin', 'ireland', 'nhl@gmail.com', '0174320'); //1

INSERT INTO COMPANY (NAME, ADDRESS, CITY, COUNTRY, EMAIL, PHONE_NUMBER)
VALUES ('google', 'silicon vally', 'mountain view', 'usa', 'gooogle@goolge.com', '+1855 855 9772'); //2

INSERT INTO COMPANY (NAME, ADDRESS, CITY, COUNTRY, EMAIL, PHONE_NUMBER)
VALUES ('mastercard.ie', 'mountain view, central park', 'dublin', 'ireland', 'info@mastercard.ie', '012178600'); //3


INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('ghodrat', 'naderi'); //1
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('naz', 'mni'); //2
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('richard', 'haythornthwaite'); //3
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('silvio', 'barzi'); //4
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('marc', 'octavio'); //5
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('larry', 'page'); //6
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('eric', 'schmidt'); //7
INSERT INTO STAKEHOLDER (FIRST_NAME, LAST_NAME) VALUES ('sergey', 'brin'); //8



//NADERHIHUB OWNERS
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (1, 1);

INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (1, 2);
//MASTERCARD OWNERS
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (2, 3);
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (2, 4);
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (2, 5);
//GOOGLE OWNERS
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (3, 6);
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (3, 7);
INSERT INTO BENEFICIAL_OWNER (COMPANY_ID, STAKEHOLDER_ID) VALUES (3, 8);
